version: '3'

services:
  wordpress:
    image: wordpress_web:latest  
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/html/wp-content
    depends_on:
      - mariadb

  mariadb:
    image: mysql-database:latest  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  wordpress-data:
  mariadb-data: