# Service für Wordpress
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80    # Port
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer  # Erlaubt externen Zugriff auf das Service

---
# PersistentVolumeClaim für Wordpress
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # 20GB Speicheranfordeung

---
# Deployment für Wordpress
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate    # Recreate Strategie
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress:4.8-apache   # Wordpress Apache Image
          name: wordpress
          env:  
            - name: WORDPRESS_DB_HOST   # MySQL Host
              value: wordpress-mysql
            - name: WORDPRESS_DB_PASSWORD # MySQL Passwort -> vom secret
              valueFrom:  
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 80   # Container-Port
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html    # Mounting auf Pfad /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
