version: '3'

services: 
  # MySQL Database
  db_mysql: 
    image: mysql:latest
    container_name: mysql_db
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - mysql-data:/var/lib/mysql
    
  # Wordpress
  wordpress:
    image: wordpress:latest
    container_name: wordpress_web
    ports: 
      - '8080:80'
    environment:
      - WORDPRESS_DB_HOST=db_mysql:3306
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-data:/var/www/html
      
volumes:
  mysql-data:
  wordpress-data:
